package com.novelty.personality;

public enum PersonalityValidationError {
    ANSWERS_REQUIRED,
    INDOOR_OUTDOOR_REQUIRED,
    SOCIAL_LEVEL_REQUIRED,
    PHYSICAL_ACTIVITY_LEVEL_REQUIRED,
    NOVELTY_LEVEL_REQUIRED,
    INTERESTS_REQUIRED,
    TOO_MANY_INTERESTS,
    INVALID_INTEREST,
    DUPLICATE_INTERESTS,
    EXECUTION_STYLE_REQUIRED,
    ANALYSIS_MODE_REQUIRED
}
